<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tip tc</name>
   <tag></tag>
   <elementGuidId>5b8e1895-8049-4efb-ad68-3f50ed5b4a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tw-btn-primary.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76de902d-dffb-4d9d-bf98-64841f915a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2a12638-0022-408c-96c1-2cb84002d837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default</value>
      <webElementGuid>2d9ab8f1-df37-4510-86a4-eaa4dcaae48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid silver-200 rounded-lg</value>
      <webElementGuid>88b23a56-5fdd-4305-ab45-82aee1dd1b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-font</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>fab875ff-91ca-4494-bc36-623f79ee6c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-h</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>d5dc7642-8e90-4cbc-a713-3d43ce37377c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-min-w</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>4df14622-4179-4cb6-ba03-8194be8a2a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>x-4</value>
      <webElementGuid>bc878afe-8c92-411a-b067-61abab0647ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>3.25 white</value>
      <webElementGuid>2a64608a-983d-4324-a7d4-559eda1a5f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếp tục</value>
      <webElementGuid>08f5000d-3b75-469a-8434-a9016e8b307b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/aside[@class=&quot;v-navigation-drawer v-navigation-drawer--fixed v-navigation-drawer--is-mouseover v-navigation-drawer--open v-navigation-drawer--right theme--light&quot;]/div[@class=&quot;v-navigation-drawer__content&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[3]/div[1]/div[1]/button[@class=&quot;tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default&quot;]</value>
      <webElementGuid>669a252a-9d2d-471b-acc6-7cbaa0a94fe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[32]</value>
      <webElementGuid>daac2c35-af9e-4f17-a2e7-c6f08633f35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/aside/div/div/div[2]/div[3]/div/div/button[2]</value>
      <webElementGuid>682e7feb-30a2-4a5b-ac81-25af57054f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trở về'])[1]/following::button[1]</value>
      <webElementGuid>2d7b960a-1366-412b-af20-4d62fcb3ffbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hàng tháng'])[1]/following::button[4]</value>
      <webElementGuid>c88466b3-d777-47d6-9362-a36e968b1a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chào mừng bạn đến với DragonX'])[1]/preceding::button[2]</value>
      <webElementGuid>596a7f9c-a60e-413d-95c9-42781bc27b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>9797cff6-14dc-4096-b646-b3474a280943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tiếp tục' or . = 'Tiếp tục')]</value>
      <webElementGuid>cfe3cc9a-f925-4b6f-897a-a78f1adc9512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
