<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_iSAVING</name>
   <tag></tag>
   <elementGuidId>8f0a3fe9-7e69-4b1c-9d4f-7e2216cd5aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idTradeContent']/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80152d69-141e-4fbf-8fdd-3c65ae27abba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-bg</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>3d6f97de-ee10-4a1a-ad8f-c7fd028b317f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid rounded-lg silver-200</value>
      <webElementGuid>3252e356-49e2-459b-9320-f70f3d4e77b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>52b26d09-91e6-4340-82a8-3604350ce8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-shadow</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>5fdb5a72-93b7-4793-968b-3b19c1f2f5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~ 1</value>
      <webElementGuid>7e5cacff-febe-49a6-a13e-50820b24c565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-justify</name>
      <type>Main</type>
      <value>between</value>
      <webElementGuid>6a33d2bd-177b-43de-9c25-aaacfaf1e0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-overflow</name>
      <type>Main</type>
      <value>hidden</value>
      <webElementGuid>6e858fbb-649a-4f94-abe2-dca31f160907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>75cf39bc-909c-416c-a465-3e744a86edef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-space</name>
      <type>Main</type>
      <value>x-2</value>
      <webElementGuid>0f38a838-af80-4b5d-90d6-153bfa236fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-600</value>
      <webElementGuid>721e9a30-d3c4-4341-81e3-ed34ac61b9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> iSAVING </value>
      <webElementGuid>02b798d1-ac2b-471c-a0a1-669248146faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTradeContent&quot;)/div[2]/div[1]/button[1]</value>
      <webElementGuid>5ce1d0e0-0f25-4f0c-8a8a-7547be8724c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div[2]/div/button</value>
      <webElementGuid>d354c94a-e4a2-4838-81fc-ce8a2ee92789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~1.037.708₫'])[1]/following::button[1]</value>
      <webElementGuid>32aa5152-20fe-4c35-87a4-709eee25a449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~628.970₫'])[1]/following::button[1]</value>
      <webElementGuid>a73a282d-9431-4dcd-a949-8021f7856a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản chính'])[1]/preceding::button[1]</value>
      <webElementGuid>7105b096-7290-45b4-aed6-a7e452ba69e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d61b08e0-7471-458b-ac43-3983955438d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' iSAVING ' or . = ' iSAVING ')]</value>
      <webElementGuid>e646de8e-5190-4efb-ad1a-e19f5e7dcf92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
