<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ti khon</name>
   <tag></tag>
   <elementGuidId>ac7757e7-0e9a-474c-bbdf-c81f5caaeb0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div/div/div/div[2]/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6eb3278c-0094-4080-be31-ddc7a488dcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>39a9bbc2-0a5c-499a-a8ef-37d0db3583e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f63ae9c8-7f8b-4785-a16c-69d1e1d59598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>53e82b08-9cbd-47d0-a390-e6c1eca396c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>before:tw-hidden v-tab</value>
      <webElementGuid>e8e28e96-c272-43f7-90cd-e4f9e964a8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>99492c2c-a094-4bf9-a60e-62ff6ecb22e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-font</name>
      <type>Main</type>
      <value>tracking-normal</value>
      <webElementGuid>6d1d1aed-93a0-4f71-819e-eacbf7a7af57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>normal-case</value>
      <webElementGuid>8175aafd-ba6a-44d5-b703-0511d59b6c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tài khoản </value>
      <webElementGuid>7cfec063-8aff-4f05-b479-560659614060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[1]/div[@class=&quot;tw-flex tw-flex-col tw-flex-1 &lt;sm:tw-px-4&quot;]/div[2]/div[1]/div[@class=&quot;v-tabs theme--light&quot;]/div[@class=&quot;v-item-group theme--light v-slide-group v-tabs-bar primary--text&quot;]/div[@class=&quot;v-slide-group__wrapper&quot;]/div[@class=&quot;v-slide-group__content v-tabs-bar__content&quot;]/div[@class=&quot;before:tw-hidden v-tab&quot;]</value>
      <webElementGuid>9ad87511-445f-40d0-8d14-a26e5379fce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div/div/div/div[2]/div/div[4]</value>
      <webElementGuid>071cd71c-7ea6-48fc-a110-8fdc24cda459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quét mã QR'])[1]/following::div[2]</value>
      <webElementGuid>f49e58b2-ec76-4e32-bc45-2eb736935582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ứng dụng DragonX'])[1]/following::div[10]</value>
      <webElementGuid>15f4b708-84da-469a-9ae5-82bf73fcce3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::div[2]</value>
      <webElementGuid>b3259b4c-ca7a-4f83-a5a6-3407a5a2fefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số tài khoản, Email hoặc Số điện thoại'])[1]/preceding::div[2]</value>
      <webElementGuid>90220030-11b9-4934-bf83-32a04e2d5583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tài khoản']/parent::*</value>
      <webElementGuid>b8384f07-37c4-4170-92fa-b02577056b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>ea9c13ab-e1f7-4d61-9a7c-eafbf7974ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Tài khoản ' or . = ' Tài khoản ')]</value>
      <webElementGuid>7d37432a-2ac2-4173-8c5c-6a4a77a8a239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
