<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DCBF  14,75 CCQ  628.970</name>
   <tag></tag>
   <elementGuidId>24aabd73-5267-473e-bf18-11210764665c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idTradeContent']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTradeContent > div > div > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73c48c24-2f90-4a93-b369-843d95fe877e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-bg</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>8cf78e1a-8073-4d0d-b690-546572e19490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid silver-200 rounded-lg</value>
      <webElementGuid>3b2d6755-44f4-4578-9b51-66d976f24a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>abf99ed5-f6a1-4240-9e51-742c4cdcca63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~ 1 col</value>
      <webElementGuid>aa5ea411-832c-4cb9-a5a9-9fb8a66f1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ad3ef5ec-ae5e-47ba-95d1-5e29e760b46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-pos</name>
      <type>Main</type>
      <value>relative</value>
      <webElementGuid>f4cbc609-7209-4ef6-8a0c-4b623dd16279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-shadow</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>b81e239e-5c54-40c2-960c-f1cbca2037b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-200</value>
      <webElementGuid>2e34643a-fafc-4aed-8611-a1d9a27eb209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DCBF  14,75 CCQ  ~628.970₫ </value>
      <webElementGuid>f386b17d-3bff-4e7a-8710-bc2db38cef0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTradeContent&quot;)/div[1]/div[1]/div[2]</value>
      <webElementGuid>0d896b7e-9493-419f-90a9-e235b818c335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div/div/div[2]</value>
      <webElementGuid>b33fe4c7-37eb-4c3e-aad7-022f1c44ac06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~80.936₫'])[1]/following::div[1]</value>
      <webElementGuid>6ed57e72-caea-4e3a-b782-c774032121be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển đổi'])[1]/following::div[6]</value>
      <webElementGuid>c3e88542-a2e1-4884-bc0c-8f2a56c94b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~1.037.708₫'])[1]/preceding::div[2]</value>
      <webElementGuid>b49e5e2b-d072-4016-90f4-bb0e59a949d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>6a40b8d2-97ee-4b11-af4d-42da6770922b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' DCBF  14,75 CCQ  ~628.970₫ ' or . = ' DCBF  14,75 CCQ  ~628.970₫ ')]</value>
      <webElementGuid>275b60d1-f3bc-49b6-921a-384573941f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
