<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DCBF  14,75 CCQ  628.970</name>
   <tag></tag>
   <elementGuidId>24aabd73-5267-473e-bf18-11210764665c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;idTradeContent&quot;]/div[1]/div/div/p[text()[contains(.,&quot;DCBF&quot;)]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTradeContent > div > div > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8900977d-d382-4da0-9ea3-086a7aa570e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-bg</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>a82d6529-e80c-475f-8406-32301b63d9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid silver-200 rounded-lg</value>
      <webElementGuid>a6ff09df-520a-4c86-b3fe-22773d7dc0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>a1501f87-6485-422d-bcd9-887c701d2394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~ 1 col</value>
      <webElementGuid>bddae4ae-e456-4e2e-84e3-5def9361cde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a515f772-250b-4e9c-9c75-19c1ccd6f9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-pos</name>
      <type>Main</type>
      <value>relative</value>
      <webElementGuid>f9aadc8a-6622-4b27-aaf2-5570fd4ec85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-shadow</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>dfa65d11-f22d-441e-914b-8a6801a00f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-200</value>
      <webElementGuid>fed0686a-d6c1-4254-9eb0-292cebccb1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DCBF  14,75 CCQ  ~628.970₫ </value>
      <webElementGuid>aa5164fd-abdb-4796-9ae4-6ecdf196295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTradeContent&quot;)/div[1]/div[1]/div[2]</value>
      <webElementGuid>0e633b68-ceb9-40ea-9c62-afe0010a336f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div/div/div[1]</value>
      <webElementGuid>8924c165-5693-4f05-9028-8c8c0dc73193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~80.936₫'])[1]/following::div[1]</value>
      <webElementGuid>94f5f5d1-9538-45f4-8426-889aad35fde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển đổi'])[1]/following::div[6]</value>
      <webElementGuid>25738627-52a6-40a5-847a-ba85762a47fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~1.037.708₫'])[1]/preceding::div[2]</value>
      <webElementGuid>b827887c-7465-423c-92d5-5c53a56e8197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>c68f6012-2b9c-44a8-9ea3-19c7efd2da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' DCBF  14,75 CCQ  ~628.970₫ ' or . = ' DCBF  14,75 CCQ  ~628.970₫ ')]</value>
      <webElementGuid>459bb653-0f47-4c27-ab97-c89c0888dfc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
