<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__otp--4</name>
   <tag></tag>
   <elementGuidId>ab5ef13f-0f0a-4dde-9aac-a0a9140bea55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-151--4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='otp-field-box--4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>915b07e8-1ebf-40d2-9700-a68baab60f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>33915cc5-2082-4137-a5bb-b8d50c2f2635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b60b7940-1bf0-442c-82e5-401a725b5d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-151--4</value>
      <webElementGuid>7060674e-4213-4f89-8014-ac2d83bed4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--4</value>
      <webElementGuid>0f998eae-711b-4738-843f-d398898c13e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>050b5beb-5574-4f11-bc0f-221ab05c47a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-151--4&quot;)</value>
      <webElementGuid>e5c83a2f-64ab-4572-9d3c-7756ba934ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-151--4']</value>
      <webElementGuid>f723878d-1501-476c-9ceb-473506f8b480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div[5]/div/div/div/input</value>
      <webElementGuid>46f5e8be-915d-4e70-ae45-3a5e1843adee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>458f17e0-33b4-4ec8-b24f-52032267fbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input-151--4']</value>
      <webElementGuid>6c3b3e68-b404-46d5-85ec-44d5da026f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
