<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-521--3</name>
   <tag></tag>
   <elementGuidId>eccea4b2-3d09-431a-b301-ce80a22cdfe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-521--3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-521--3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2fada69-d61f-4ef6-8919-4fb4aac380f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>2629e02c-d2b6-4c6c-bfa2-c7a4aa77cb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0748a661-450d-4033-aac7-6e74431b3913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-521--3</value>
      <webElementGuid>d30887af-b9ea-4076-a781-a292cb9a10d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--3</value>
      <webElementGuid>0332a37f-e61a-4f63-ade4-86ce46e4df0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-521--3&quot;)</value>
      <webElementGuid>27839d2d-91da-427f-b215-b03b039d5b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-521--3']</value>
      <webElementGuid>e74dfdde-328d-47cb-92b6-b0e344bb86c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div[4]/div/div/div/input</value>
      <webElementGuid>0689cdc6-0da5-4ea4-9a9e-023543d65178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>3c85f1b4-b2bc-419a-b6e1-b8187ec9714a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input-521--3']</value>
      <webElementGuid>d2aa110d-afd7-4c33-8865-42a8fe932a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
