<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-521--0</name>
   <tag></tag>
   <elementGuidId>8b2ffe97-b4cf-49e5-a5d3-7e13c141c819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-521--0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-521--0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02ed8778-759d-47c3-a83e-5712aa60c53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>b498faae-738c-47b6-bfc3-f93b52102e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2ca9582e-782d-4275-80d8-d4086152b25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-521--0</value>
      <webElementGuid>009f14d7-82f9-460c-a43c-f630596a7bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--0</value>
      <webElementGuid>ee034906-4997-48f9-9da3-b6860fa9375b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-521--0&quot;)</value>
      <webElementGuid>f77a7cc9-069c-4ecd-bdd8-cd9479c506a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-521--0']</value>
      <webElementGuid>875b5614-2888-486a-a50d-e7da6c6fe415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>c3d62616-c1d1-4536-99fd-9b5ddbe28aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>1fb409ed-f3d3-4aa3-91f0-140f05fb68a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input-521--0']</value>
      <webElementGuid>1c3d8d9a-367a-4f11-8d22-a4f1051e2ebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
