<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-521--2</name>
   <tag></tag>
   <elementGuidId>bb2fb56b-9faa-46f2-83fb-421b9afc962d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-521--2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-521--2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1444de1f-276b-4ff4-b278-0048f5f8ed54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>5766b45a-41b7-4f6f-9011-a4e8d5d82755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6cd9fe58-da66-4968-a00a-c260170b6210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-521--2</value>
      <webElementGuid>70dde7db-7f71-4a3b-b980-b70b6ccf658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--2</value>
      <webElementGuid>a72a5d76-036b-4de9-98ee-e5db7348a550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-521--2&quot;)</value>
      <webElementGuid>5a3f6446-23ba-4002-8103-0da3c80438be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-521--2']</value>
      <webElementGuid>f69e03ec-b494-416e-bf11-b2c4236ebf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div[3]/div/div/div/input</value>
      <webElementGuid>6a6b803b-1e27-4b31-8eb0-06badfe15cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>3cd264d0-a9aa-4573-806e-739f247a4ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input-521--2']</value>
      <webElementGuid>842f5723-6092-4866-922a-4d6e7954a6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
