<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-521--5</name>
   <tag></tag>
   <elementGuidId>356e1d8c-7d1a-4cd6-ae3f-e8d191362ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-521--5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-521--5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4464dba-6a8e-420f-b840-a51f7a358dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>26f9281c-0a45-4325-8451-c2e4ad0c7578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>af190da8-896c-4b7f-9064-9f06be7aa3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-521--5</value>
      <webElementGuid>731c7884-3eef-456e-84df-0cce1da11006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--5</value>
      <webElementGuid>6c5afac0-dbd9-496d-87d9-38ea01da450c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-521--5&quot;)</value>
      <webElementGuid>c42040b1-bf06-4218-976e-ef8ae4e9a275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-521--5']</value>
      <webElementGuid>f36caad1-42e9-4ceb-9d02-a10613c834f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div[6]/div/div/div/input</value>
      <webElementGuid>038e921a-192a-4369-8c7c-aa0b6a9e0e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>4d92d065-dacf-4ba0-9713-dcdca1460ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input-521--5']</value>
      <webElementGuid>b3d46608-56b8-496b-a93c-c991cf576bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
