<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-521--1</name>
   <tag></tag>
   <elementGuidId>b6f58373-2680-4055-bd9c-fd98e4b06ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-521--1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-521--1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d2f703b-5ab1-4bec-a5a4-85fa1a43644a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>b82f3f74-0a68-41a0-9c94-e0f2ea9f2c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>20602c8a-42ff-4aea-aca1-16c325b16853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-521--1</value>
      <webElementGuid>b053972c-789a-4c18-ae61-dbb576d8f0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--1</value>
      <webElementGuid>b8b65f8a-2463-455c-bb1e-600367e12cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-521--1&quot;)</value>
      <webElementGuid>f805a076-babc-4c5c-b008-dfc9a7080ea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-521--1']</value>
      <webElementGuid>9ccc0a18-c092-45a9-9a44-8ebc31169931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>bf6c2f37-cc80-4ec0-93da-b32a5bcce0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4c357e6f-b407-462a-8eed-ac498b6466b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'input-521--1']</value>
      <webElementGuid>5bae7869-1a4f-4ebb-ba29-d5cd1d6f3520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
