<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_lenh</name>
   <tag></tag>
   <elementGuidId>3d0713a2-c2ee-43b6-bfa7-208c23003039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[3]/div/div/table/tbody/tr[3]/td[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52f3e485-1d6a-4dd8-866b-e90dfc6876ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>3.25</value>
      <webElementGuid>17dbb2ba-7a54-4b46-89f4-35988b25885f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>07/08/2023</value>
      <webElementGuid>be00e5a5-6099-4eae-8871-fe147fa8dc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[1]/div[3]/div[@class=&quot;v-data-table c-data-table-header c-data-table-wrapper c-data-table-row-selectable c-data-table-order-smartinvest tw-flex tw-h-full tw-flex-col tw-justify-between v-data-table--fixed-header v-data-table--has-bottom theme--light&quot;]/div[@class=&quot;v-data-table__wrapper&quot;]/table[1]/tbody[1]/tr[3]/td[@class=&quot;text-start&quot;]/span[1]</value>
      <webElementGuid>9af14c2e-65fe-4c90-bc1c-4cc271c44cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div/table/tbody/tr[3]/td[6]/span</value>
      <webElementGuid>55239d6f-e69b-4d6b-ab55-db72c5865e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/following::span[1]</value>
      <webElementGuid>c02d06b7-6a6e-4bdf-97af-e2cf2f5a69f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mua'])[3]/following::span[3]</value>
      <webElementGuid>ed46c8c3-0d0f-4d73-acc5-e4e11be16608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang xử lý'])[1]/preceding::span[1]</value>
      <webElementGuid>a03c8f19-b03a-4506-99ef-aee2f5868286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DCBF'])[2]/preceding::span[2]</value>
      <webElementGuid>6df56e0a-dfae-43ec-a94d-320ed3880480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='07/08/2023']/parent::*</value>
      <webElementGuid>5a493dd6-d692-43e5-8fc8-2831ee192b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/span</value>
      <webElementGuid>3dcd4814-451f-4690-953b-12cd44358df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '07/08/2023' or . = '07/08/2023')]</value>
      <webElementGuid>ca71f10d-ca20-47a6-83a4-922b9f508c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
