<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_()_svg-icon svg-fill</name>
   <tag></tag>
   <elementGuidId>0e530800-2c34-4d71-9482-9735054101a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tw-relative.v-card.v-sheet.theme--light > button.v-btn.v-btn--icon.v-btn--round.theme--light.v-size--default > span.v-btn__content > svg.svg-icon.svg-fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='DCIP'])[6]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>1123a53d-00c9-420f-a72f-2df60d95088e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>c443aaa9-c4dc-481d-94ce-90b6789215c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-h</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>54b94999-87d0-497c-8bc0-8c6e4e0e988c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-stroke</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>74f8b827-270c-4fb2-9d2a-0431d3a57308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>shark</value>
      <webElementGuid>5bc42136-3528-43f8-9d55-8ba327fbd17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-w</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9996a287-d31a-4aa5-ba32-c70dc9425f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-icon svg-fill</value>
      <webElementGuid>4f868dc3-568d-4176-a7e7-ea6f960208ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-menu__content theme--light v-menu__content--fixed menuable__content__active tw-rounded-lg tw-min-w-0 tw-w-72&quot;]/div[@class=&quot;tw-relative v-card v-sheet theme--light&quot;]/button[@class=&quot;v-btn v-btn--icon v-btn--round theme--light v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/svg[@class=&quot;svg-icon svg-fill&quot;]</value>
      <webElementGuid>f24a0acb-3a38-4579-9610-25ee27e1ed7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DCIP'])[6]/following::*[name()='svg'][1]</value>
      <webElementGuid>7d5d3e9c-463a-4771-ba69-18906122c038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp tục'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c67f6b6f-903b-40e9-a0fc-316c54fbd105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
