<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_S lnh</name>
   <tag></tag>
   <elementGuidId>e6fce8e8-025a-4bac-9f77-06f3d31a987e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='order']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0be568d1-569f-49eb-97df-73a888388267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/vi/order</value>
      <webElementGuid>176fc35d-53c1-4fce-9229-cc61c952b5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-group aside-navigation</value>
      <webElementGuid>07566509-b48c-42fc-83fb-28fdfcfebe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order</value>
      <webElementGuid>1c0381ce-cae9-4ad5-8e27-924738cd5570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-align</name>
      <type>Main</type>
      <value>items-center</value>
      <webElementGuid>33261e79-6b25-4e49-8076-0c5ce53ad86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>rounded-lg</value>
      <webElementGuid>08199cf8-d747-42ba-b66e-73a6e37e95d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~</value>
      <webElementGuid>c13e40e2-a0ed-4dae-8355-4e1bbe1a87fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-h</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>cb9edbe9-3f6e-46a2-980c-f8ecb186e0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-hover</name>
      <type>Main</type>
      <value>text-white bg-seagreen-700</value>
      <webElementGuid>15b99a00-7805-4b8b-bb31-c31e5ea668bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>x-3</value>
      <webElementGuid>4f977b49-b5c4-4b1c-bc40-509eaf46dcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-space</name>
      <type>Main</type>
      <value>x-3</value>
      <webElementGuid>8dc8e437-5c1b-499e-a10a-c1abc1caff63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>3.25 gray-600</value>
      <webElementGuid>022bad57-8c9f-41ef-a404-790ab70fea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-150</value>
      <webElementGuid>1063eea6-7e4e-4def-b862-b7a5992ca0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sổ lệnh</value>
      <webElementGuid>2b0b5f93-ea98-43c1-a2f3-b93076c9bfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order&quot;)</value>
      <webElementGuid>e2699d14-9ebb-468f-94db-bbd1097076fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='order']</value>
      <webElementGuid>8c5dd0af-2901-43ad-9c7f-56bd48b7fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='asideMenu']/a[3]</value>
      <webElementGuid>83a21d7f-b812-42e1-bd02-94bb3790ae5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh mục'])[1]/following::a[1]</value>
      <webElementGuid>37569e6d-6b3a-4d59-ae18-08d96328985b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/following::a[2]</value>
      <webElementGuid>a671bf9e-b8db-4f4d-923a-51cbcf6f6b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm'])[1]/preceding::a[1]</value>
      <webElementGuid>e81f7c44-f805-4031-bbd2-d8eec541f4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/vi/order')]</value>
      <webElementGuid>9e42c5a4-46c2-46a7-85d2-fa4898a4919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>7117f865-967a-4374-8eda-075eca9b3b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/vi/order' and @id = 'order' and (text() = 'Sổ lệnh' or . = 'Sổ lệnh')]</value>
      <webElementGuid>56fef009-223d-423c-8f4f-2274c3ba573f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
