<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng nhp</name>
   <tag></tag>
   <elementGuidId>0ec30edc-3889-4581-aa60-3ec1b3583a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tw-btn-primary.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70527beb-150f-4d83-92e1-9381b3d484d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a95b6d7b-5209-4696-a634-f13ea5a2f2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default</value>
      <webElementGuid>a06b82b3-1ff3-415e-b777-c7a0d334e82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>idFormLogin</value>
      <webElementGuid>603db99c-7c3d-4212-812f-7e5d3fc12413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>rounded-lg</value>
      <webElementGuid>b7c817b0-d6fe-43d1-84df-5d6aa3dff3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-h</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4ccf5ce6-5901-4512-9457-8c2b84bfa55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-m</name>
      <type>Main</type>
      <value>t-6</value>
      <webElementGuid>68e6b498-fe49-47c9-9dc9-ee72a9d452dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>x-4</value>
      <webElementGuid>13bbb03a-a7e3-4f3d-82b2-37f4ce9fb153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>3e402eb3-1264-40b7-a832-f2fa41b879f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-w</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>c256dbde-90ca-4edd-8a0e-d61f9ab4d9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Đăng nhập </value>
      <webElementGuid>7d5b1b8f-a16c-4efa-b7dc-e5f5325d0e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idFormLogin&quot;)/button[@class=&quot;tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default&quot;]</value>
      <webElementGuid>4cc79e20-2a70-4b27-aa5a-5cc43a2a84b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>4d647e9c-abe8-43e8-926e-e53883485fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/button</value>
      <webElementGuid>61810bd7-8cb6-4967-b9f0-0b2d834570da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quên mã PIN đăng nhập?'])[1]/following::button[1]</value>
      <webElementGuid>11de6ece-b88b-4dd3-bee0-0ba1e0737353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ghi nhớ tài khoản'])[1]/following::button[1]</value>
      <webElementGuid>ffde62a9-8597-4cb0-b37b-8f955727a81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin chương trình'])[1]/preceding::button[1]</value>
      <webElementGuid>10ca1c00-c7a7-438f-99dc-f944687f4985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>1b3ac058-ac52-4ed8-9b1b-0cbc051ba185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @form = 'idFormLogin' and (text() = ' Đăng nhập ' or . = ' Đăng nhập ')]</value>
      <webElementGuid>682692b5-3b85-49a6-9ba9-540671ebf5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
