<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-151--0</name>
   <tag></tag>
   <elementGuidId>fa06c397-6aed-4e28-89aa-6d6c7ffd7079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-151--0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-151--0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9336f2cb-1cce-4b01-b4c6-8ccc16fb4528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>e73dcc30-950e-4130-b7fc-03b5f7f46ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8cd35699-9716-48b8-919a-10cc6fa68aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-151--0</value>
      <webElementGuid>a78e8be9-e40e-4f5a-bc2c-4fb5cde3990f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-field-box--0</value>
      <webElementGuid>4b840438-d97c-44c7-877b-d40fdea13e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fc35e12-8bf9-44e3-9ca5-8be032f1ca60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-151--0&quot;)</value>
      <webElementGuid>494c11df-9e8b-4205-a1af-ee4b4271b322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-151--0']</value>
      <webElementGuid>4850fff8-8755-405b-95f3-4c6067aeff61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>acc2f01a-4fe2-47de-b9fb-38381bccb6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>0dd863d0-5c24-45f0-ae90-2dbfa316d800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input-151--0']</value>
      <webElementGuid>5dab3368-0f9f-4554-8fb1-f8a4d6d950a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
