<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S ti khon, Email hoc S in thoi_input-115</name>
   <tag></tag>
   <elementGuidId>b95b43af-2ba5-4179-81c7-1e3c3d5059c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-115']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-115</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>448e3acc-6763-468f-8334-8b2ec68dabe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-115</value>
      <webElementGuid>a0c6656d-b9e0-4103-95cc-2bb7490d228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51990484-9efd-4793-9ffb-6f001256c06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-115&quot;)</value>
      <webElementGuid>f3bf436c-e9c9-42df-9348-0970658b274e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-115']</value>
      <webElementGuid>5878ba0d-dded-402f-a36f-1f360f4e4471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/div/div/div/div/input</value>
      <webElementGuid>e1301db7-99be-4967-8a22-915717f8c669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>529ffbc6-4e84-4821-8e0a-bf689ceba884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-115' and @type = 'text']</value>
      <webElementGuid>255f0cbd-1db8-4092-b950-46c423c79f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
