<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S ti khon, Email hoc S in thoi_input-115</name>
   <tag></tag>
   <elementGuidId>b95b43af-2ba5-4179-81c7-1e3c3d5059c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-115</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-115']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88e6d05b-a122-452b-b188-6ffd338399a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-115</value>
      <webElementGuid>8e5cc70e-3a88-4075-a916-e39dec9921dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10404418-43f6-4d33-8d9f-359a5948d817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-115&quot;)</value>
      <webElementGuid>675e2ee6-5648-4506-b1b5-c1ccfdef2307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-115']</value>
      <webElementGuid>b492bc2a-7959-4cb7-a0b7-f5337e1c88b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/div/div/div/div/input</value>
      <webElementGuid>f60e25b8-ab54-4c3d-8bf4-3586b2f561d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>bee2a5c2-b2fb-4879-8374-e1a71b855aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-115' and @type = 'text']</value>
      <webElementGuid>870d786f-4af8-444d-8fe4-f28ee912dfde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
