<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M PIN ng nhp_input-119</name>
   <tag></tag>
   <elementGuidId>d3a730d5-ec69-45b0-bec7-66349032b2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-119']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-119</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>606ae618-036f-4d7b-bb47-08c3c6aaeecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-119</value>
      <webElementGuid>2af0613c-7f70-41f9-8215-7ac8379120c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b29aea50-74cf-4951-82c5-5a480f5587b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-119&quot;)</value>
      <webElementGuid>5a2bd213-e680-497d-87d0-737c18e25b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-119']</value>
      <webElementGuid>8e78e4b4-48a7-4b07-addc-52f9fe12242f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/div[2]/div/div/div/input</value>
      <webElementGuid>7005d634-ce92-48eb-ba3a-a9ef3b7b9be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4c29c3c4-a9fa-46d0-88ca-4a34d5709ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-119' and @type = 'password']</value>
      <webElementGuid>dabc6261-8607-496f-a6cc-2ec71e01a08e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
