<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>38b866ab-433b-4b45-a4a1-913407011ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tw-relative.v-card.v-sheet.theme--light > button.v-btn.v-btn--icon.v-btn--round.theme--light.v-size--default > span.v-btn__content > svg.svg-icon.svg-fill > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>2ff6b648-5c1f-4629-b697-6ba1cc6350f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>648c83dd-f239-4ac2-b861-7cb47d981455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M18 6 6 18M6 6l12 12</value>
      <webElementGuid>5cf37d41-9a06-4b95-bdfd-ab805bcb630d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>aa037201-642a-44b0-850f-409c1ff4d149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>aadab3c7-8e26-4ff5-8f05-503b7f5564f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>a4f74ef4-3a27-4d71-b689-a8481b2363e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>01660575-ad9e-41e5-853e-e686de6b4529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-menu__content theme--light v-menu__content--fixed menuable__content__active tw-rounded-lg tw-min-w-0 tw-w-72&quot;]/div[@class=&quot;tw-relative v-card v-sheet theme--light&quot;]/button[@class=&quot;v-btn v-btn--icon v-btn--round theme--light v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/svg[@class=&quot;svg-icon svg-fill&quot;]/path[1]</value>
      <webElementGuid>ba254ddf-c7a5-42b3-8493-94b2dee49f0e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
