<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Xc nhn</name>
   <tag></tag>
   <elementGuidId>25fb98d4-cef0-417b-821a-fd57af31cb24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[4]/div/div/div[3]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tw-btn-primary.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default > span.v-btn__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f74bf00-0026-4b3a-be55-97754765689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>271bc941-c215-4fd1-be8c-7556fd6e72f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xác nhận </value>
      <webElementGuid>da1c38ec-e66a-498f-88ea-99ed14d34f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog tw-rounded-lg tw-shadow-none tw-min-w-90 tw-w-auto v-dialog--active v-dialog--persistent v-dialog--scrollable&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__actions&quot;]/button[@class=&quot;tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>70e92445-8ffe-4034-8fee-061d5bad31a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div/div[3]/button/span</value>
      <webElementGuid>0fd64940-59e0-4eb0-bf05-28106d7ecfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xác thực giao dịch'])[1]/following::span[2]</value>
      <webElementGuid>b8ceab86-9600-4abb-b57e-209cebc5c93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xác nhận']/parent::*</value>
      <webElementGuid>1404619a-ef94-4575-a3c6-38f2809b3193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>9a4b5350-5d66-479a-bc87-9b3fb4f3313a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Xác nhận ' or . = ' Xác nhận ')]</value>
      <webElementGuid>1365953b-a583-4486-ba27-d0f496fd0846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
