<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tip tc</name>
   <tag></tag>
   <elementGuidId>e119a3cf-d510-41b7-a2f9-7d3a7a4776b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.tw-btn-primary.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>010fd65a-ad85-4898-bc0b-1601914107af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0ff7921-3ad8-41bb-8be4-51bdeec27f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default</value>
      <webElementGuid>1d5bfce8-0d8f-4024-a207-a26b1357a12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid silver-200 rounded-lg</value>
      <webElementGuid>208fe035-48b5-45ea-9727-372cf06420c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-font</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>988787db-0fcf-4a8a-9d4a-b2882295ecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-h</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e13210fa-d6a3-4ae8-87f2-6e96653f45cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-min-w</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>9ad3712e-040d-47f7-bf8b-5c70084115e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>x-4</value>
      <webElementGuid>e3c4ba56-2f55-4406-9f5e-b39ce721fae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>3.25 white</value>
      <webElementGuid>4dc21117-c11a-423c-b05a-6b44d3a68cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếp tục</value>
      <webElementGuid>defebaaf-988a-42ab-ab61-9810ccc4452e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[1]/div[1]/div[3]/div[1]/div[1]/button[@class=&quot;tw-btn-primary v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default&quot;]</value>
      <webElementGuid>5077dba1-28d9-4138-bf89-f6cb62f64e4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>0bf21350-8b4d-44f7-8601-3479c63b51fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[3]/div/div/button[2]</value>
      <webElementGuid>bd089e84-2742-4d36-b5ce-1029f852082a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trở về'])[1]/following::button[1]</value>
      <webElementGuid>ea6c87d2-c91a-46b1-af7e-a64b1a9a310c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian chốt lệnh'])[1]/following::button[2]</value>
      <webElementGuid>f9182795-56c2-4eda-b682-750a4852be2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>56f4e5c8-5c7d-425f-b3d1-2864b8e742f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tiếp tục' or . = 'Tiếp tục')]</value>
      <webElementGuid>5cb6df2f-1d9f-435e-877b-94c37e4a1fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
