<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_iSAVING</name>
   <tag></tag>
   <elementGuidId>a0bfb0cc-796d-426c-b71e-48ea9c64475f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idTradeContent']/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64ef7afa-33e5-450d-bb0e-96fe2ed01700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-bg</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>8a4f3a11-9e76-42d6-9c55-e17dcd2c5d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid rounded-lg silver-200</value>
      <webElementGuid>219d6ce8-ba74-4ebf-97dc-35cea16cd3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>2d11f640-4a15-4849-906a-1455004ed72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-shadow</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>b3efaa2e-0cd4-4e01-97c1-808f7a88a158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~ 1</value>
      <webElementGuid>611a6701-731e-48a7-baf9-452657ba5161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-justify</name>
      <type>Main</type>
      <value>between</value>
      <webElementGuid>94d03d24-e7a8-4696-b84f-1de764610c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-overflow</name>
      <type>Main</type>
      <value>hidden</value>
      <webElementGuid>0053d493-ce4b-421d-99c4-0bd9bfa62251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>765ad82b-12d8-4f87-8635-b0184cf0b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-space</name>
      <type>Main</type>
      <value>x-2</value>
      <webElementGuid>b9f2393f-e087-4107-9ac3-7afa83791a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-600</value>
      <webElementGuid>ebbb7f86-94e3-4f01-870a-13dc4f3ba4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> iSAVING </value>
      <webElementGuid>7870a552-2220-455b-9199-44726e7f6e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTradeContent&quot;)/div[2]/div[1]/button[1]</value>
      <webElementGuid>72d24779-1f8e-4303-8470-7f03056df256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div[2]/div/button</value>
      <webElementGuid>77293a9c-18c9-418a-8ddd-99e4962f582f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~1.037.708₫'])[1]/following::button[1]</value>
      <webElementGuid>fefd8de5-4cb6-4860-8c05-20da77f7f77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~628.970₫'])[1]/following::button[1]</value>
      <webElementGuid>5ab01791-6384-4a44-bf98-44fd8c1d32a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản chính'])[1]/preceding::button[1]</value>
      <webElementGuid>57075e1e-b139-4ee0-aba8-4db8e390a560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>539b958f-36af-45c9-b04b-7c9ac3042df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' iSAVING ' or . = ' iSAVING ')]</value>
      <webElementGuid>c42b1fa2-2dc5-469e-a080-1a31d67af9ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
