<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bn  t 5 lnh mua Linh hot vi cng ngy giao dch. Chng ti s khp tng s tin m bn chuyn vo 1 lnh v cc lnh cn li s t ng b hy</name>
   <tag></tag>
   <elementGuidId>4ca89945-25f5-4c86-8946-21b1f197bdcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-html-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-html-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9e66159-8741-4b4d-867d-50068480a4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>5f6f9c2d-0a56-45c6-91ac-dbec44ddedc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-html-container</value>
      <webElementGuid>aa4c35f9-fe76-4e65-bd7d-cc3777e8e7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bạn đã đặt 5 lệnh mua Linh hoạt với cùng ngày giao dịch. Chúng tôi sẽ khớp tổng số tiền mà bạn chuyển vào 1 lệnh và các lệnh còn lại sẽ tự động bị hủy.</value>
      <webElementGuid>c58a5282-85c4-4a15-93f8-edb952d389ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-html-container&quot;)</value>
      <webElementGuid>9f341565-ac48-420c-9e52-c961281520a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']</value>
      <webElementGuid>55195c32-8fdf-41c5-b6cb-5509bb3a0bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu ý'])[1]/following::div[1]</value>
      <webElementGuid>eb794661-42d0-44fa-a720-94855f5d4e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>684cf0ec-24eb-45c6-ab9c-95c41d518249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[4]</value>
      <webElementGuid>a3085f72-1e1b-4e48-b275-7443ab9f7a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bạn đã đặt 5 lệnh mua Linh hoạt với cùng ngày giao dịch. Chúng tôi sẽ']/parent::*</value>
      <webElementGuid>001e7801-9fb9-40ed-92af-9ea395142713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]</value>
      <webElementGuid>3554105e-4209-40d8-8b35-1a859b89b182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'swal2-html-container' and (text() = 'Bạn đã đặt 5 lệnh mua Linh hoạt với cùng ngày giao dịch. Chúng tôi sẽ khớp tổng số tiền mà bạn chuyển vào 1 lệnh và các lệnh còn lại sẽ tự động bị hủy.' or . = 'Bạn đã đặt 5 lệnh mua Linh hoạt với cùng ngày giao dịch. Chúng tôi sẽ khớp tổng số tiền mà bạn chuyển vào 1 lệnh và các lệnh còn lại sẽ tự động bị hủy.')]</value>
      <webElementGuid>2038aad7-eccc-46ba-b90e-d8c8adaba940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
