<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DCBF  16,75 CCQ  628.970</name>
   <tag></tag>
   <elementGuidId>c4c4c452-5f5c-4b50-b0ec-8557ce0b45a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idTradeContent']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTradeContent > div > div > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c98724e7-b430-4df1-99cc-344be7291d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-bg</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>1cbf8dfe-f999-46e3-b177-1cdc0e0ef110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>~ solid silver-200 rounded-lg</value>
      <webElementGuid>4f1d161e-4e62-4a4f-b572-82567b2aa5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>fb6c21c9-3c16-4518-bcd8-f1d194a8a6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>~ 1 col</value>
      <webElementGuid>2434ac27-911c-4ec3-a941-252c36c21e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>096ef99a-19ac-4236-b47c-7bd2f8e7b269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-pos</name>
      <type>Main</type>
      <value>relative</value>
      <webElementGuid>16ec8da9-064e-4f67-bbf5-1ba070dbba18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-shadow</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>885d5ac3-99cb-4e8f-917d-b3e4d81ce924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-transition</name>
      <type>Main</type>
      <value>~ duration-200</value>
      <webElementGuid>febde0f1-353e-4176-a761-2d0931371ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DCBF  16,75 CCQ  ~628.970₫ </value>
      <webElementGuid>2fd74f58-a904-40c7-870d-b6bf7e23226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTradeContent&quot;)/div[1]/div[1]/div[2]</value>
      <webElementGuid>fc92c9f3-5964-435c-a0e2-6d73719a97a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div/div/div[2]</value>
      <webElementGuid>3eb2d0f0-2be1-46ac-86da-55e4568ef0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~80.936₫'])[1]/following::div[1]</value>
      <webElementGuid>11548e0f-8197-431e-8055-24c6b667fd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển đổi'])[1]/following::div[6]</value>
      <webElementGuid>89baa7a8-428b-4d25-af61-e46be93da5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~1.037.708₫'])[1]/preceding::div[2]</value>
      <webElementGuid>98cc1751-19e9-4d20-b053-a045e3c40aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>e0dbec75-bf9c-4095-bb8a-2e85e9064c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' DCBF  16,75 CCQ  ~628.970₫ ' or . = ' DCBF  16,75 CCQ  ~628.970₫ ')]</value>
      <webElementGuid>142e9cb1-0ff3-4268-ae07-b0b8cc0caa39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
