<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2</name>
   <tag></tag>
   <elementGuidId>1010052f-8cd9-445c-84db-14cab24c3cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-card__text > div > div > div:nth-of-type(2) > div > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f64c835-f4f5-4ad4-a561-875310be999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-border</name>
      <type>Main</type>
      <value>solid silver-200
        r
        b</value>
      <webElementGuid>2621aa20-0917-4668-bd0b-2f24bd1ce2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-cursor</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>5a7a842b-827b-413c-826e-6bfe66007e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-flex</name>
      <type>Main</type>
      <value>center 1</value>
      <webElementGuid>8ea5a8de-c27e-4cbd-8020-47ee74ede3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-font</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>82c16f99-5ab4-4183-90d5-e0992194726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-p</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c491bcb6-4e2d-4fb2-a8aa-7d2a0838772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tw-text</name>
      <type>Main</type>
      <value>lg gray-900</value>
      <webElementGuid>06a1acf3-e712-4b7e-beaa-c06df8621513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previous-position</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>33ad8179-0425-4189-9eb6-8689e1d6d188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>06e9dbc4-287c-487a-9a52-12cb60d9986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog tw-border-none tw-rounded-lg tw-shadow-none tw-max-w-102 v-dialog--active v-dialog--persistent v-dialog--scrollable&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[1]/div[1]/div[2]/div[1]/div[2]</value>
      <webElementGuid>c4daf91c-5d6d-4dcc-b234-48de8297001a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>dfa8d6b5-6e6f-486b-a18a-fdcdb7d62590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[8]/following::div[4]</value>
      <webElementGuid>0cd6f6fd-cf4d-422b-8aec-8122032bdc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[7]/following::div[8]</value>
      <webElementGuid>547cd0e1-d21b-4222-9c9c-7de445a65b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>fb44a9d3-4d50-435a-b853-71360dc3a985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2' or . = '2')]</value>
      <webElementGuid>55836a0c-c359-4fad-bf6a-a6c6e179cdaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
