<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M PIN ng nhp_input-119</name>
   <tag></tag>
   <elementGuidId>d5d5d86b-82e4-417a-a417-19a0c846adc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-119']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-119</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f673e0bc-84f5-4ccb-bf2c-77858b59db15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-119</value>
      <webElementGuid>4dba338b-b8b2-484c-9eec-0130bd42dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b4506156-62cd-446e-bfb4-d6bd9dd94f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-119&quot;)</value>
      <webElementGuid>32bc55b5-a9e7-4da2-a9ef-8c3a5855cebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-119']</value>
      <webElementGuid>286de44e-d8d8-4071-9bf8-6896b217816a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/div[2]/div/div/div/input</value>
      <webElementGuid>8b86d61a-60fa-4e3a-8fe6-ad8c60c0704b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>866df5a8-35d0-42df-b8cc-7ccffc7339c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-119' and @type = 'password']</value>
      <webElementGuid>37f01d79-3b62-4baa-8dc1-05f6db2ec2d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
