<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S ti khon, Email hoc S in thoi_input-115</name>
   <tag></tag>
   <elementGuidId>fe006e33-66ce-40e6-a5c7-4e3fd07c4384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-115']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-115</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa716dfd-5a8a-45a7-a186-8a2365a60535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-115</value>
      <webElementGuid>6cc054ca-476c-439b-9385-033dad282b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ab3fadb-bee2-40c3-ab1a-f68add5fb36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-115&quot;)</value>
      <webElementGuid>9bbebc5d-f5d4-4961-b221-a7eda4236830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-115']</value>
      <webElementGuid>ae8ac237-9019-4541-bd14-6deabe6dc740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='idFormLogin']/div/div/div/div/input</value>
      <webElementGuid>a75bd8a8-b475-4dca-a8b4-c42f91676862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>ab3c0512-f26d-4477-ab5a-4867c8c3df04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-115' and @type = 'text']</value>
      <webElementGuid>41d38adc-5a55-4f2b-a590-9c6d1b1071ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
