<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gi tr bn (CCQ)_input-493</name>
   <tag></tag>
   <elementGuidId>46767438-d845-40e3-8509-55b92023eb0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-493']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-493</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68ec16c8-898f-44ec-9da5-4b9ed2800267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-493</value>
      <webElementGuid>1f5edc14-ad3f-4155-bbbd-6b4e1444ffad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4dbd0f75-3f96-4b9e-bb2a-d797b249a23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maska-value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b1ba8150-8fc2-4ffb-bd6c-ed273be834a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-493&quot;)</value>
      <webElementGuid>3afd627a-95fb-4b48-8a73-5ee419e5f781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-493']</value>
      <webElementGuid>be81eef4-b812-45c8-afad-144afd3e93dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idTradeContent']/div[3]/form/div[2]/div/div/div/input</value>
      <webElementGuid>b35b30e4-8d34-49e7-a01d-61b26be172fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>35de451c-80c3-4d2f-a75f-c7d1b47a5821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-493' and @type = 'tel']</value>
      <webElementGuid>3e64d7db-3e65-4781-a7d3-bdaff7fafc15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
